// <auto-generated />
using MerakiAutomation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MerakiAutomation.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201119140738_InitialSeedTest")]
    partial class InitialSeedTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("MerakiAutomation.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kevin",
                            Title = "Network Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brandon",
                            Title = "Network Senior"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gabe",
                            Title = "Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
